spring:
  application:
    name: AccountManagement
  profiles:
    active: prod

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

jwt:
  secret: your-secret-key-that-is-at-least-256-bits-long-for-hs256-algorithm-please-change-in-production
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000

google:
  client-id: 1059865245376-lva4cp3hcvsslk4vcqghadh7c9c4t817.apps.googleusercontent.com

management:
  endpoints:
    web:
      base-path: /account-management/actuator
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.komplikevych.AccountManagement: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

